      - name: Test Sky TG24 con geobypass Italia
        run: |
          yt-dlp \
            -v \
            --xff IT \
            --extractor-args "youtube:player_client=android" \
            -F "https://www.youtube.com/watch?v=DBkiOifHkVE"
